未普化的標準南京話
nk2028/qieyun-examples pull request #24
Opened 2021-07-05 13:24 UTC by uliloewi

@ayaka14732 
推導南京音做好了。請合併。

2021-07-05 14:36 UTC, ayaka14732 commented
「廣州音」用「音」是因為「廣州音」比較常見，而「上海話」就用「話」

![image](https://user-images.githubusercontent.com/68557794/124487471-577b2380-dde1-11eb-85f2-c5fa082cee56.png)

![image](https://user-images.githubusercontent.com/68557794/124487493-619d2200-dde1-11eb-815a-60b732507982.png)

2021-07-05 14:46 UTC, uliloewi commented
> 「廣州音」用「音」是因為「廣州音」比較常見，而「上海話」就用「話」
> 
> ![image](https://user-images.githubusercontent.com/68557794/124487471-577b2380-dde1-11eb-85f2-c5fa082cee56.png)
> 
> ![image](https://user-images.githubusercontent.com/68557794/124487493-619d2200-dde1-11eb-815a-60b732507982.png)

行。按習慣用“話”

2021-07-08 16:08 UTC, uliloewi commented
@ayaka14732 
推導程序已上傳，請測試一下能不能運行。

2021-08-01 02:44 UTC, ayaka14732 requested changes

2021-08-01 02:44 UTC, ayaka14732 commented on langjin.js
> +  if (is('端母')) return is('二等') ? 'z' : 'd';
通常端組沒有二等，不要寫特例

```suggestion
  if (is('端母')) return 'd';
```

2021-08-01 02:44 UTC, ayaka14732 commented on langjin.js
> +  if (is('定母')) return is('二等') ? 'ch' : is('平聲') ? 't' : 'd'; // 平送氣仄不送氣；“窀”爲ch
不要寫特例

```suggestion
  if (is('定母')) return is('平聲') ? 't' : 'd'; // 平送氣仄不送氣
```

2021-08-01 02:44 UTC, ayaka14732 commented on langjin.js
> +  if (is('知母')) return is('麻韻 三等 或 灰韻') ? 'd' : is('庚耕韻') ? 'z' : 'zh'; // 知組平翹律；“爹”&“𩬳”爲d
不要寫特例

```suggestion
  if (is('知母')) return is('庚耕韻') ? 'z' : 'zh'; // 知組平翹律
```

2021-08-01 09:47 UTC, uliloewi commented on langjin.js
> +  if (is('端母')) return is('二等') ? 'z' : 'd';
已改

2021-08-01 09:48 UTC, uliloewi commented on langjin.js
> +  if (is('定母')) return is('二等') ? 'ch' : is('平聲') ? 't' : 'd'; // 平送氣仄不送氣；“窀”爲ch
已改

2021-08-01 09:48 UTC, uliloewi commented on langjin.js
> +  if (is('知母')) return is('麻韻 三等 或 灰韻') ? 'd' : is('庚耕韻') ? 'z' : 'zh'; // 知組平翹律；“爹”&“𩬳”爲d
已改

2021-08-01 11:06 UTC, ayaka14732 requested changes

2021-08-01 11:06 UTC, ayaka14732 commented on langjin.js
> + * 南京音本是清末以前標準官話的基礎音系，和中古音有嚴格的對應關系。故有上表。本程序展示此對應關系。
關係

```suggestion
 * 南京音本是清末以前標準官話的基礎音系，和中古音有嚴格的對應關係，故有上表。本程序展示此對應關係。
```

2021-08-01 11:06 UTC, ayaka14732 commented on README.md
> +- 推導廣州話 (Extrapolated Cantonese): `gwongzau.js`
先不要改這個

2021-08-01 11:06 UTC, ayaka14732 commented on langjin.js
> +  if (is('知母')) return is('麻韻 三等') ? 'd' : is('庚耕韻') ? 'z' : 'zh'; // 知組平翹律；
```suggestion
  if (is('知母')) return is('麻韻 三等') ? 'd' : is('庚耕韻') ? 'z' : 'zh'; // 知組平翹律
```

2021-08-01 11:07 UTC, ayaka14732 commented on langjin.js
> +  if (is('溪母')) return is('二等 皆韻 或 二等 開口 江韻 入聲') ? 'k' : is(不顎化) ? 'k' : 'q';
顎化是否類似普通話？如果類似普通話，可以此處一律寫 k，然後在後面判斷

2021-08-01 12:16 UTC, uliloewi commented on langjin.js
> +  if (is('溪母')) return is('二等 皆韻 或 二等 開口 江韻 入聲') ? 'k' : is(不顎化) ? 'k' : 'q';
不太像。很多不顎化

2021-08-03 12:58 UTC, ayaka14732 approved these changes

2021-08-03 13:01 UTC, ayaka14732 requested changes
The file `LangjinOldAlgorithmAndTest.js` should be removed, or move to a different branch.

2021-08-03 13:16 UTC, uliloewi commented
> The file `LangjinOldAlgorithmAndTest.js` should be removed, or move to a different branch.

已刪除

2021-08-03 13:24 UTC, ayaka14732 approved these changes

2021-08-03 13:24 UTC, merged